### Shiritori Game !

This challenge is an English twist on the Japanese word game Shiritori. The basic premise is to follow two rules:

- The first character of the next word must match the last character of the previous word.
- The word must not have already been said.

Sample Input
- 4
- Jawed dowry yash home
- eagle eagle oh house elated
- dongle excited danger doubt
- ajesh how worst torture

Sample O/p:
- True
- False
- False
- True

In [8]:
n = int(input())
for i in range(n):
    s = input().split()
    status = True
    for j in range(1,len(s)):
        second_word = s[j]
        first_word = s[j-1]
        if(second_word[0] != first_word[-1]):
            status = False
            break
            
    for j in s:
        if s.count(j) > 1:
            status = False
            break
            
    if(status):
        print("Valid")
    else:
        print("Invalid")
        

4
dowry yash how what
Valid
eagle eagle eagle
Invalid
typo orange
Valid
pavan isro
Invalid


In [9]:
import numpy as np

In [10]:
# Check your Numpy Version
np.__version__

'1.16.2'

In [13]:
# Creating an Array
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [17]:
# Accessing Individual Elements From The Array
print(a1[0],a1[1],a1[2])

1 2 3


In [18]:
# Creating 2-d Array
a2 = np.array([[4,5,6],[9,10,16]])
print(a2)

[[ 4  5  6]
 [ 9 10 16]]


In [26]:
# Access Individual Elements
a2[1,1] / a2[1,0]

1.1111111111111112

In [37]:
# Create a 3d Array
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [35]:
# Accessing individual Elements
a3[1,0,0] + a3[0,0,2]

13

In [44]:
# Performing Vectorized Operations on Array
a1 = a1*10
a1

array([10, 20, 30, 40, 50])

In [45]:
# To Know what kind of data that your array has
a1.dtype

dtype('int64')

In [46]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2 = arr2 * 12
print(arr2)

[[12 24 36]
 [48 60 72]]


In [47]:
arr2.dtype

dtype('int64')

In [48]:
twod = np.array([1,2,3],dtype = "float")
print(twod)

[1. 2. 3.]


In [54]:
# AStype() - Changes the data type of the 
# existing array
print("Existing values are of type ",twod.dtype)
twod = twod.astype('int')
print("The Modified Array looks like ",twod)
twod = twod.astype('str')
print("The Modified Array looks like ",twod)
twod.dtype

Existing values are of type  <U21
The Modified Array looks like  [1 2 3]
The Modified Array looks like  ['1' '2' '3']


dtype('<U21')

In [55]:
a = np.array([1,2,3],dtype = 'float')
print(a.dtype) # float64
a = a.astype('int')
print(a.dtype) #int64
a = a.astype('str')
print(a.dtype) #<u21

float64
int64
<U21


In [60]:
# Create a string array and convert it to an int
# array
a = np.array(['1','23','32'],dtype='str')
a = a.astype('int')
print(a)

[ 1 23 32]


In [68]:
a = np.array([1,2,3],dtype = 'int')
a = a.astype('str')
a = a.astype('float')
a = a.astype('int')
a

array([1, 2, 3])

In [69]:
b = a.tolist()
b

[1, 2, 3]

In [74]:
# Creating a boolean array
b = np.array([0,1,2,3,"","vvit"],dtype='bool')
print(b)

[False  True  True  True False  True]


In [81]:
a3.ndim

3

In [82]:
a3.shape

(2, 3, 3)

In [83]:
a3.size

18

In [88]:
a = np.array(range(1,11))
a[:4]

array([1, 2, 3, 4])

In [97]:
a = np.array([[1,2,3],[4,5,6]])
print("The original Array is\n",a)
print("Reverse only the rows\n",a[::-1,])
print("Reverse the  Columns\n",a[:,::-1])
print("Reverse all the elements\n",a[::-1,::-1])

The original Array is
 [[1 2 3]
 [4 5 6]]
Reverse only the rows
 [[4 5 6]
 [1 2 3]]
Reverse the  Columns
 [[3 2 1]
 [6 5 4]]
Reverse all the elements
 [[6 5 4]
 [3 2 1]]


In [103]:
a3[::-1,::-1,::-1]

array([[[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [116]:
# Boolean indexing
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a>2
a[b]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
# Missing Values --> np.nan
# Infinite Values --> np.inf
a = np.array([1,2,3,np.inf,np.nan,5,6,7],dtype="str")
a

array(['1', '2', '3', 'inf', 'nan', '5', '6', '7'], dtype='<U3')

In [125]:
# Calculating mean(), min(),max()
a2 = np.array([[-1,0,-1],[0,9,-10],[256,-8,288]])
print("The Mean of this array is : ",a2.mean())
print("The Min Value in this array is: ",a2.min())
print("The Max value in this array is: ",a2.max())

The Mean of this array is :  59.22222222222222
The Min Value in this array is:  -10
The Max value in this array is:  288


In [128]:
print("The Min element across the rows is ",np.amin(a2,axis = 1))

The Min element across the rows is  [ -1 -10  -8]


In [130]:
print("The Min element across columns is ",np.amin(a2,axis = 0))

The Min element across columns is  [ -1  -8 -10]


In [132]:
a2

array([[ -1,   0,  -1],
       [  0,   9, -10],
       [256,  -8, 288]])

In [133]:
np.cumsum(a2,axis = 0)

array([[ -1,   0,  -1],
       [ -1,   9, -11],
       [255,   1, 277]])

In [134]:
np.cumsum(a2,axis = 1)

array([[ -1,  -1,  -2],
       [  0,   9,  -1],
       [256, 248, 536]])

In [135]:
a = np.array([1,2,3])
np.cumsum(a)

array([1, 3, 6])

In [136]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [137]:
np.cumsum(a3,axis=0)   # (2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 13, 15],
        [17, 19, 21],
        [23, 25, 27]]])

In [138]:
np.cumsum(a3,axis=1)

array([[[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]],

       [[10, 11, 12],
        [23, 25, 27],
        [39, 42, 45]]])

In [139]:
np.cumsum(a3,axis=2)

array([[[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]],

       [[10, 21, 33],
        [13, 27, 42],
        [16, 33, 51]]])

In [144]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a[:3].copy()
b[1]=4
print("Modified b is :",b)
print("A Will not be modified ",a)

Modified b is : [1 4 3]
A Will not be modified  [ 1  2  3  4  5  6  7  8  9 10]


In [145]:
a.shape

(10,)

In [147]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [150]:
a = a.reshape(-1,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [151]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [152]:
a[0,0]

1

In [155]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = a.reshape(2,2,-1)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [156]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [158]:
a.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [164]:
b = a.flatten()
b[8] = -1
b
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [168]:
c = a.ravel()
c[8] = -1
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8, -1],
        [10, 11, 12]]])

In [169]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [170]:
a = np.arange(5,20)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [171]:
a = np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [173]:
b = np.linspace(start = 1,stop = 50, num = 10)
b

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [176]:
np.zeros([13])
# We can create any desired shape array with all zeros in 
# it

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [179]:
np.ones([6,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [181]:
a = np.arange(3)
a

array([0, 1, 2])

In [182]:
np.tile(a,3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [183]:
np.repeat(a,2)

array([0, 0, 1, 1, 2, 2])

In [189]:
np.random.rand(2,4)

array([[0.79051568, 0.00816942, 0.97453658, 0.02083992],
       [0.64506079, 0.99899661, 0.97650631, 0.65411192]])

In [190]:
np.random.randn(2,4)

array([[ 1.07428089, -1.71209262, -0.71249623,  2.24078545],
       [-0.3714919 , -1.54280711, -0.30485276,  0.12640202]])

In [194]:
np.random.randint(10,20,[2,4])

array([[12, 16, 10, 12],
       [16, 11, 10, 19]])

In [197]:
np.random.random()

0.43505997172765465

In [198]:
np.random.rand()

0.3469315290700311

In [202]:
np.random.choice([1,2,3,4],10)

array([2, 2, 4, 1, 4, 1, 3, 2, 2, 1])

In [234]:
a = np.array([11,11,22,12,11,22,33])
b,counts = np.unique(a,return_counts = True)
m = counts.max()
l = np.argmax(counts)
b[l]

11

In [217]:
n = "andhrapradesh"
n = list(n)
a = np.array(n)
b,counts = np.unique(a,return_counts = True)
counts.max()

3

In [230]:
a = np.random.randint(10,30,[10])
print("The Array is ",a)
b = np.where(a>15)
print("The Condition is going right at these places ",b)

The Array is  [23 14 23 27 14 19 21 22 29 15]
The Condition is going right at these places  (array([0, 2, 3, 5, 6, 7, 8]),)


In [258]:
p = "https://raw.githubusercontent.com/pavankumart46/pythonSolutions/master/sample.csv"
b = np.genfromtxt(p,
                  delimiter = ',',
                  skip_header = True,
                  filling_values = -1,
                  dtype='str' )
b[:3]

array([['18', '8', '307', '130', '3504', '12', '70', '1',
        '"chevrolet chevelle malibu"'],
       ['15', '8', '350', '165', '3693', '11.5', '70', '1',
        '"buick skylark 320"'],
       ['18', '8', '318', '150', '3436', '11', '70', '1',
        '"plymouth satellite"']], dtype='<U38')

In [247]:
q = np.array([[1,2,3.4,'vvit'],[3.5,6,'engine',5]],
             dtype='str')
q

array([['1', '2', '3.4', 'vvit'],
       ['3.5', '6', 'engine', '5']], dtype='<U6')

In [254]:
a = np.array([[1,2,3],[4,5,6]])
np.savetxt("filename.csv",a,fmt='%10.5f',delimiter = ",")

In [267]:

np.savetxt("export.csv",
           b,
           fmt='%s %s %s %s %s %s %s %s %s',
           delimiter = ',',
           header="first,second,third,fourth,fifth,sixth,seventh,eigth,ninth")

In [270]:
a = np.zeros([3,3])
b = np.ones([3,3])
c = np.concatenate([a,b],axis = 0)
print("For Axis 0 \n",c)
d = np.concatenate([a,b],axis = 1)
print("For Axis 1 \n",d)

For Axis 0 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
For Axis 1 
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [272]:
np.vstack([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [273]:
np.hstack([a,b])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [274]:
np.r_[a,b]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [275]:
np.c_[a,b]

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Presentation Link for Numpy: 

https://docs.google.com/presentation/d/17nFjzUrjJ0aJsHB0bUXZ6e7x-dUJH9Izq1ZKntwx7p0/edit?usp=sharing